CI: update github workflow config
antimatter-dao/bas-template-bsc pull request #6
Opened 2022-08-15 03:33 UTC by 0xe3b0c4

### Description

update github workflow config 

### Changes

Notable changes: 
* upgrade build environment to `ubuntu-22.04`
* upgrade golang to `1.17`
* add docker image build config

2022-08-23 05:46 UTC, 0xe3b0c4 commented
## remove old package require personal access tokens

1. create github token (need  `read:packages`  and  `delete:packages` ) 

![scopes](https://user-images.githubusercontent.com/110295932/186079420-8c00beec-5466-490d-b60a-94611ef9b5d1.png)


2. Project setting add actions secret (secret name: `AUTO_DELETE_OLD_VERSION_PAT` )

![setting](https://user-images.githubusercontent.com/110295932/186078678-922223a9-f2cb-4cd0-a0cd-f986bfd90400.png)

2022-08-27 07:31 UTC, RichardBrown123go commented on .github/workflows/build-devel-image.yml
> +    types:
Add the branch is a better option.

2022-08-27 07:33 UTC, RichardBrown123go requested changes
LGTM
Only a few suggestion.

2022-08-27 07:43 UTC, RichardBrown123go commented
@matterfun Would you follow this PR?
The CI needs to update some secrets in repo settings.

2022-09-01 10:22 UTC, RichardBrown123go approved these changes
Great job.
Thanks for your contribution.

2022-09-01 10:23 UTC, merged